### ISSUE TITLE
All serializations other than nquads fail

### ISSUE THREAD

**Issue by jrvosse** [CLARIAH/COW#153]
Using the "buurt.csv" file from the tutorial, all formats other than nquads fail to serialize. I get the same behavior on my other CSV files.

```
shell> cow_tool convert --format turtle buurt.csv
...
Something went wrong, skipping buurt.csv.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/cow_csvw/csvw_tool.py", line 79, in __init__
    g.serialize(destination=output_file,
  File "/opt/homebrew/lib/python3.11/site-packages/rdflib/graph.py", line 1118, in serialize
    serializer.serialize(stream, base=base, encoding=encoding, **args)
  File "/opt/homebrew/lib/python3.11/site-packages/rdflib/plugins/serializers/turtle.py", line 241, in serialize
    self.startDocument()
  File "/opt/homebrew/lib/python3.11/site-packages/rdflib/plugins/serializers/turtle.py", line 306, in startDocument
    self.write(self.indent() + "@prefix %s: <%s> .\n" % (prefix, uri))
  File "/opt/homebrew/lib/python3.11/site-packages/rdflib/plugins/serializers/turtle.py", line 171, in write
    self.stream.write(text.encode(self.encoding, "replace"))
TypeError: write() argument must be str, not bytes
```

**Comment by pvgenuchten** [comment]
same problem here, any news?
