### ISSUE TITLE
RFC 3987 non compliance error

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/COW#28]
Hi, 

it appears the iri-baker stopped baking iri's. E.g. when convert on the guerry.csv data, the error below is reported. I've tested this on multiple already converted files and all of them complain about the iri's.

```
administrators-MacBook-Pro-3:testcow RichardZ$ cow_tool convert guerry.csv
Converting guerry.csv to RDF
Initializing converter for guerry.csv
Processes: 4
Chunksize: 5000
Quotechar: '"'
Delimiter: ','
Encoding : 'ascii'
Taking encoding, quotechar and delimiter specifications into account...
Starting conversion
Opening CSV file for reading
Running in 4 processes
Process PoolWorker-1, nr 0, 5000 rows
Row: 0
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
dept/1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cow_csvw/converter/csvw.py", line 364, in _burstConvert
    result = c.process(count, rows, chunksize)
  File "/usr/local/lib/python2.7/site-packages/cow_csvw/converter/csvw.py", line 429, in process
    s = self.expandURL(self.aboutURLSchema, row)
  File "/usr/local/lib/python2.7/site-packages/cow_csvw/converter/csvw.py", line 594, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `dept/1` to valid IRI
TypeError in multiprocessing... falling back to serial conversion
Opening CSV file for reading
Starting in a single process
Row: 0
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
dept/1
Something went wrong, skipping guerry.csv.
```

**Comment by rlzijdeman** [comment]
Hi, this actually boils down to #22 . @albertmeronyo let me try and implement that fix now

**Comment by rlzijdeman** [comment]
Right, so I updated all files in both /sdh-public-datasets and /sdh-private-hisco. I've tested 3 files from sdh-public and they now work perfectly. However, the files from sdh-private-hisco still won't converge. The error is no longer about the iri_baker anymore so I'm closing this issue and will create a new issue for the HISCO files
