### ISSUE TITLE
valueUrl not working

### ISSUE THREAD

**Issue by tkuhn** [CLARIAH/COW#80]
Using the common countries.csv example and replacing the line

    "datatype": "string"

for the column `Country` with

    "valueUrl": "http://example.com/{Country}"

I expect to get object URIs of the form `http://example.com/Qatar` instead of the previous literals `"Qatar"`, but I am getting errors like these:

```
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
None
Traceback (most recent call last):
  File "/home/tk/.local/lib/python3.7/site-packages/iribaker/__init__.py", line 31, in to_iri
    rfc3987.parse(iri, rule='IRI')
  File "/home/tk/.local/lib/python3.7/site-packages/rfc3987.py", line 462, in parse
    raise ValueError('%r is not a valid %r.' % (string, rule))
ValueError: 'None' is not a valid 'IRI'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 762, in expandURL
    iri = iribaker.to_iri(url)
  File "/home/tk/.local/lib/python3.7/site-packages/iribaker/__init__.py", line 47, in to_iri
    raise Exception("The argument you provided does not comply with"
Exception: The argument you provided does not comply withRFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 587, in process
    p = self.expandURL(c.csvw_propertyUrl, row)
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 765, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `None` to valid IRI
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
None
Traceback (most recent call last):
  File "/home/tk/.local/lib/python3.7/site-packages/iribaker/__init__.py", line 31, in to_iri
    rfc3987.parse(iri, rule='IRI')
  File "/home/tk/.local/lib/python3.7/site-packages/rfc3987.py", line 462, in parse
    raise ValueError('%r is not a valid %r.' % (string, rule))
ValueError: 'None' is not a valid 'IRI'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 762, in expandURL
    iri = iribaker.to_iri(url)
  File "/home/tk/.local/lib/python3.7/site-packages/iribaker/__init__.py", line 47, in to_iri
    raise Exception("The argument you provided does not comply with"
Exception: The argument you provided does not comply withRFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 587, in process
    p = self.expandURL(c.csvw_propertyUrl, row)
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 765, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `None` to valid IRI
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
None
Traceback (most recent call last):
  File "/home/tk/.local/lib/python3.7/site-packages/iribaker/__init__.py", line 31, in to_iri
    rfc3987.parse(iri, rule='IRI')
  File "/home/tk/.local/lib/python3.7/site-packages/rfc3987.py", line 462, in parse
    raise ValueError('%r is not a valid %r.' % (string, rule))
ValueError: 'None' is not a valid 'IRI'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 762, in expandURL
    iri = iribaker.to_iri(url)
  File "/home/tk/.local/lib/python3.7/site-packages/iribaker/__init__.py", line 47, in to_iri
    raise Exception("The argument you provided does not comply with"
Exception: The argument you provided does not comply withRFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 587, in process
    p = self.expandURL(c.csvw_propertyUrl, row)
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 765, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `None` to valid IRI
... done
```

**Comment by rlzijdeman** [comment]
Hi @tkuhn, I am not a software engineer, so this will be a bit vague: Currently the version under Python 2.7 ought to work and can be installed via pip. The Python 3 version does currently not process the valueUrls properly, because of an undocumented difference between Python 2.7 and Python 3 in a library  the CoW inherits.

**Comment by tkuhn** [comment]
Right, I forgot to mention that I am using Python 3.

Also, it should have been

    valueUrl": "http://example.com/{Country}"

above (I forgot the curly bracket part, which I added now).

However, it doesn't work with Python 2 either. I am getting these errors:

```
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
None
Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 587, in process
    p = self.expandURL(c.csvw_propertyUrl, row)
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 765, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `None` to valid IRI
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
None
Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 587, in process
    p = self.expandURL(c.csvw_propertyUrl, row)
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 765, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `None` to valid IRI
The argument you provided does not comply with RFC 3987 and is not parseable as a IRI(there is no scheme or no net location part)
None
Traceback (most recent call last):
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 587, in process
    p = self.expandURL(c.csvw_propertyUrl, row)
  File "/home/tk/Packages/COW/src/converter/csvw.py", line 765, in expandURL
    raise Exception(u"Cannot convert `{}` to valid IRI".format(url))
Exception: Cannot convert `None` to valid IRI
... done
```

**Comment by rlzijdeman** [comment]
@albertmeronyo see above. I can't replicate the error myself under 2.7, but do get a
```https://iisg.amsterdam/{_row} does not look like a valid URI, trying to serialize this will break.```
error.

**Comment by tkuhn** [comment]
I think I found a solution for this:

It seems that `valueUrl`only works if `propertyUrl` is explicitly specified as well, like so:

    "valueUrl": "http://example.com/{Country}", 
    "propertyUrl": "http://example.com/hasCountry", 

And then I had to catch some NameErrors: https://github.com/peta-pico/COW/commit/d84ef8c84ccf4d5d3a5373de8574dd75e1d4d344

Now it seems to work for me.

**Comment by melvinroest** [comment]
I've been able to reproduce the issue with: https://github.com/CLARIAH/COW/blob/master/examples/imf_gdppc.csv
